#lang info
(define collection "hackasm")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define racket-launcher-names '("hackasm"))
(define racket-launcher-libraries '("main.rkt"))
(define scribblings '(("scribblings/hackasm.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(Reuben Thomas))
(define license '(GPLv3+))
